// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG2wHCrGrwi2WQPmXt7c_9kxsISAfx8Ek',
    appId: '1:504797579917:web:ea946b046cc3f33703b0c4',
    messagingSenderId: '504797579917',
    projectId: 'pose-perfect-0',
    authDomain: 'pose-perfect-0.firebaseapp.com',
    storageBucket: 'pose-perfect-0.firebasestorage.app',
    measurementId: 'G-L337B5QRY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj1v-bE-OKl1Qm_t0sdhYaAsATSfvAza8',
    appId: '1:504797579917:android:f54d9b40bb1adcb803b0c4',
    messagingSenderId: '504797579917',
    projectId: 'pose-perfect-0',
    storageBucket: 'pose-perfect-0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlmRb-YzM4ddB2P3xuafmQImc29fsYUeo',
    appId: '1:504797579917:ios:242bb9f8e4b615e603b0c4',
    messagingSenderId: '504797579917',
    projectId: 'pose-perfect-0',
    storageBucket: 'pose-perfect-0.firebasestorage.app',
    iosClientId: '504797579917-62q68clucfado7p2a2rioegl7t12mdg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogaTwo',
  );
}
